import './globals.css'
import { Comfortaa, Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import DynamicNavBar from '@/components/NavBarLoader'

const inter = Comfortaa({ subsets: ['latin'] })






export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({

  children,
}: {
  children: React.ReactNode
}){
  return (
    <html lang="en" className='h-full'>      
      <body className="h-full">
        <DynamicNavBar/>
        <div className='pt-[100px] min-h-full'>
           
          {children}
          
        </div>
        <Footer/>
      </body>
    </html>
  )
}
