import './globals.css'
import { Comfortaa, Inter } from 'next/font/google'
import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer'

const inter = Comfortaa({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-full'>      
      <body className="h-full">
        <div className='min-h-full'>
          <NavBar/>
          {children}
          
        </div>
        <Footer/>
      </body>
    </html>
  )
}
